apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - encode-deployment.yaml
  - prefill-deployment.yaml
  - decode-deployment.yaml
  - ../../../recipes/modelserver/common

configurations:
  - namereference.yaml
