apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../recipes/modelserver/base/single-host/pd/vllm
  - encode-deployment.yaml
  - shared-ec-cache-pvc.yaml

namePrefix: e-p-d-disaggregation-nvidia-gpu-vllm-

images:
  - name: REPLACE_MODEL_SERVER_IMAGE
    newName: docker.io/vllm/vllm-openai
    newTag: v0.19.1-x86_64-cu130

labels:
  - pairs:
      llm-d.ai/model: qwen2.5-vl-7b-instruct
      llm-d.ai/guide: e-disaggregation
      llm-d.ai/accelerator-variant: gpu
      llm-d.ai/accelerator-vendor: nvidia
      inference.networking.k8s.io/engine-type: vllm
    includeSelectors: true
    includeTemplates: true
    fields:
      - version: v1
        kind: ServiceAccount
        path: metadata/labels
        create: true
      - group: apps
        version: v1
        kind: Deployment
        path: metadata/labels
        create: true
      - group: apps
        version: v1
        kind: Deployment
        path: spec/selector/matchLabels
        create: true
      - group: apps
        version: v1
        kind: Deployment
        path: spec/template/metadata/labels
        create: true

patches:
  - path: patch-encode.yaml
  - path: patch-prefill.yaml
  - path: patch-decode.yaml
