apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-variant-autoscaler-wva-variantautoscaling-config
data:
  # Set this to your managed Prometheus endpoint for GKE.
  PROMETHEUS_BASE_URL: "https://prometheus.monitoring.svc.cluster.local:9090"
  PROMETHEUS_TLS_INSECURE_SKIP_VERIFY: "false"
