apiVersion: apps/v1
kind: Deployment
metadata:
  name: encode
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: modelserver
          command:
          - vllm
          - serve
          args:
          - --model
          - Qwen/Qwen3-VL-2B-Instruct
          - --port
          - "8000"
          - --disable-access-log-for-endpoints
          - /health,/metrics,/v1/models
          - --enforce-eager
          - --mm-encoder-only
          - --no-enable-prefix-caching
          - --ec-transfer-config
          - '{"ec_connector": "ECCPUConnector", "ec_role": "ec_producer"}'
          env:
          - name: PORT
            value: "8000"
          - name: VLLM_LOGGING_LEVEL
            value: DEBUG
          - name: VLLM_EC_SIDE_CHANNEL_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: VLLM_EC_SIDE_CHANNEL_PORT
            value: "5610"
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                key: HF_TOKEN
                name: llm-d-hf-token
                optional: true
          - name: TRITON_CACHE_DIR
            value: /.triton
          - name: VLLM_USE_V1
            value: "0"
          - name: DP_SIZE
            value: "1"
          - name: DP_SIZE_LOCAL
            value: "1"
          - name: HF_HOME
            value: /model-cache
          resources:
            limits:
              cpu: "4"
              memory: 64Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "4"
              memory: 64Gi
              nvidia.com/gpu: "1"
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - mountPath: /.cache
              name: torch-compile-cache
            - mountPath: /.triton
              name: triton-cache
            - mountPath: /.config
              name: vllm-config
            - mountPath: /model-cache
              name: model-cache
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 120
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 20Gi
        - name: torch-compile-cache
          emptyDir: {}
        - name: triton-cache
          emptyDir: {}
        - name: vllm-config
          emptyDir: {}
        - name: model-cache
          emptyDir:
            sizeLimit: 250Gi
