apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "multi-nic-compute",
              "namespace": "openshift-sriov-network-operator"
            }
          ]
    spec:
      containers:
        - name: modelserver
          command:
          - vllm
          - serve
          args:
          - --model
          - Qwen/Qwen3-VL-2B-Instruct
          - --port
          - "8000"
          - --tensor-parallel-size
          - "1"
          - --block-size
          - "128"
          - --kv-transfer-config
          - '{"kv_connector":"NixlConnector", "kv_role":"kv_both"}'
          - --disable-uvicorn-access-log
          - --max-model-len
          - "32000"
          env:
          - name: VLLM_LOGGING_LEVEL
            value: DEBUG
          - name: VLLM_NIXL_SIDE_CHANNEL_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: DP_SIZE
            value: "1"
          - name: TP_SIZE
            value: "1"
          - name: DP_SIZE_LOCAL
            value: "1"
          - name: HF_HOME
            value: /model-cache
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                key: HF_TOKEN
                name: llm-d-hf-token
                optional: true
          ports:
            - name: nixl
              containerPort: 5600
              protocol: TCP
          resources:
            limits:
              cpu: "4"
              memory: 64Gi
              nvidia.com/gpu: "1"
              rdma/roce_gdr: "1"
            requests:
              cpu: "4"
              memory: 64Gi
              nvidia.com/gpu: "1"
              rdma/roce_gdr: "1"
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - mountPath: /.cache
              name: torch-compile-cache
            - mountPath: /.triton
              name: triton-cache
            - mountPath: /.config
              name: vllm-config
            - mountPath: /model-cache
              name: model-cache
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 120
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 20Gi
        - name: torch-compile-cache
          emptyDir: {}
        - name: triton-cache
          emptyDir: {}
        - name: vllm-config
          emptyDir: {}
        - name: model-cache
          persistentVolumeClaim:
            claimName: llm-d-model-cache
