router:
  extraServicePorts:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081

  epp:
    pluginsConfigFile: "e-pd-config.yaml"
    pluginsCustomConfig:
      e-pd-config.yaml: |
        apiVersion: llm-d.ai/v1alpha1
        kind: EndpointPickerConfig
        plugins:
        - type: disagg-headers-handler
        - type: always-disagg-multimodal-decider
        - type: disagg-profile-handler
          parameters:
            deciders:
              encode: always-disagg-multimodal-decider
        - type: encode-filter
        - type: decode-filter
        - type: queue-scorer
        - type: max-score-picker
        - type: no-hit-lru-scorer
        schedulingProfiles:
        - name: encode
          plugins:
          - pluginRef: encode-filter
          - pluginRef: queue-scorer
            weight: 2
          - pluginRef: max-score-picker
        - name: decode
          plugins:
          - pluginRef: decode-filter
          - pluginRef: queue-scorer
            weight: 2
          - pluginRef: no-hit-lru-scorer
            weight: 2
          - pluginRef: max-score-picker

  modelServers:
    matchLabels:
      llm-d.ai/guide: "e-disaggregation"
