apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-shared-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client-pokprod
  resources:
    requests:
      storage: 50Gi

# Made with Bob
