apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-shared-storage
  namespace: epd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ibm-spectrum-scale-fileset
  resources:
    requests:
      storage: 50Gi
