apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  template:
    spec:
      initContainers:
        - name: routing-proxy
          args:
            - --port=8000
            - --vllm-port=8200
            - --kv-connector=nixlv2
            - --ec-connector=ec-nixl
            - --zap-log-level=1
            - --secure-proxy=false
          image: ghcr.io/revit13/llm-d-router-disagg-sidecar:dev-451239f8c7c6498ae1f9723d5f1ee8058098de93
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: sidecar
              protocol: TCP
          resources: {}
          restartPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
