apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 8
  template:
    spec:
      containers:
        - name: modelserver
          command: ["vllm", "serve"]
          args:
            - "Qwen/Qwen3-VL-32B-Instruct"
            - "--disable-access-log-for-endpoints=/health,/metrics,/v1/models"
            - "--tensor-parallel-size=2"
            - "--port=8200"
            - "--ec-transfer-config"
            - '{"ec_connector": "ECCPUConnector", "ec_role": "ec_consumer"}'
          resources:
            limits:
              cpu: "16"
              memory: 256Gi
              nvidia.com/gpu: "2"
            requests:
              cpu: "8"
              memory: 128Gi
              nvidia.com/gpu: "2"
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
            - mountPath: /.cache
              name: torch-compile-cache
            - mountPath: /.triton
              name: triton-cache
            - mountPath: /.config
              name: config-cache
            - mountPath: /shared-ec-cache
              name: shared-ec-cache
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 120
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 20Gi
        - name: torch-compile-cache
          emptyDir: {}
        - name: triton-cache
          emptyDir: {}
        - name: config-cache
          emptyDir: {}
        - name: shared-ec-cache
          persistentVolumeClaim:
            claimName: shared-ec-cache
