apiVersion: llmd.ai/v1alpha1
kind: VariantAutoscaling
metadata:
  name: optimized-baseline-nvidia-gpu-vllm-decode
  labels:
    inference.optimization/acceleratorName: "H100"
    llm-d.ai/model: "Qwen3-32B"
    llm-d.ai/inference-serving: "true"
    llm-d.ai/guide: "optimized-baseline"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: optimized-baseline-nvidia-gpu-vllm-decode
  modelID: "Qwen/Qwen3-32B"
  variantCost: "10.0"
