apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- squid-config.yaml
- deployment.yaml

labels:
- pairs:
    cache-implementation: squid

images:
- name: ubuntu/squid
  newTag: 6.1-23.10_beta
