apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Deployment
    name: multimedia-downloader
  patch: |
    - op: add
      path: /spec/template/spec/securityContext
      value:
        runAsNonRoot: true
        fsGroup: 13
    - op: add
      path: /spec/template/spec/containers/0/securityContext
      value:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsUser: 13
